<div class="registro" style="margin: 0 auto; width: 50%;">
<h2 style="text-align: center; padding-top: 20px;">TERMS &amp; CONDITIONS OF SALE</h2>
<p></p>
<p>All order subject to acceptance by A.M. &amp; CO.</p>
<p><br>Prices subject to change without notice.<br>FOB. Factory, Mexico, D.F.</p>
<p><br>The company reserves the right to withdraw or modify models, without prior notification.</p>
<p><br><strong>CREDIT TERMS</strong><br>A.M. &amp; CO. may cancel or change credit terms as it deems necessary, and may request partial or complete payment in&nbsp;advance.</p>
<p><br><strong>CUSTOM ORDERS</strong><br>A. We reserve the right to accept, refuse or cancel a custom order at any time, should the customer’s stipulations&nbsp;compromise A.M. CO. commitment to fine design and quality, or should such stipulations lead to unforeseen production&nbsp;problems.<br>B. Custom orders are not subject to cancellation by customer.<br>C. There are no warranties that extend beyond the description in any order acknowledgement.<br>D. Any change from standard design releases A.M. CO. form product liability.</p>
<p><br><strong>DIMENSIONS</strong><br>Furniture dimensions printed on catalog pages or in this specification manual are not always exact. As we continually&nbsp;examine and refine production processes, we strive to make the specification manual re"ect current sizes, <span style="text-decoration: underline;">but if</span><span>&nbsp;</span><span style="text-decoration: underline;">dimensions are critical, the customer bears the responsibility for expressly informing the factory when the order is&nbsp;</span><span></span><span style="text-decoration: underline;">placed</span>.</p>
<p><br><strong>ORDER CONFIRMATIONS</strong><br>The factory acknowledgement is the agreement between the customer and A.M. &amp; CO. and supersedes all prior or&nbsp;written statements. Acknowledged orders may be changed only by mutual and written agreement.</p>
<p><br><strong>CANCELLATION REQUESTS</strong><br>All cancellation requests are subject to factory approval.</p>
<p><br><strong>SHIPPING PROCEDURES</strong><br>When provided, A.M. &amp; CO will ship in accordance with customer instructions. If not specified, A.M. &amp; CO. will exercise its&nbsp;best judgement in selecting a carrier on behalf of the customer.&nbsp;All shipments must be consigned to a business address with adequate facilities.</p>
<p><br><strong>TRANSPORTATION CLAIMS</strong><br>When an order has passed final inspection and is consigned to a commercial trucker or common carrier at our factory,&nbsp;we have fulfilled our responsibility.</p>
<p><br><strong>MERCHANDISE CLAIMS</strong><br>Merchandise claims must be made within 30 days after receipt of goods. All field repairs must be authorized by A.M. &amp;&nbsp;CO. in order to be paid.</p>
<p><br><strong>LIMITED WARRANTY</strong><br>A.M. &amp; CO. warrants standard catalog product for one year from the date of invoice against defects in workmanship&nbsp;when put to ordinary use. This warranty does not cover damage or inquiry caused whole or in part by unreasonable&nbsp;use or abusive use, by failure to provide necessary or reasonable care or repair, or by accident, alteration, misuse,&nbsp;tampering or negligence by anyone other than A.M. &amp; CO. Due to variations in color, texture or grain, the products are&nbsp;not warranted against such variation.</p>
</div>