ALTER TABLE `noticia_per` 
ADD COLUMN `ubicacion` ENUM('SUPERIOR_IZQUIERDO', 'SUPERIOR_DERECHO', 'CENTRO', 'INFERIOR_IZQUIERDO', 'INFERIOR_DERECHO') NULL AFTER `costo`;

ALTER TABLE `noticia_rev` 
ADD COLUMN `ubicacion` ENUM('SUPERIOR_IZQUIERDO', 'SUPERIOR_DERECHO', 'CENTRO', 'INFERIOR_IZQUIERDO', 'INFERIOR_DERECHO') NULL AFTER `costo`;
