
CREATE TABLE `files_pdfs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `path_image` VARCHAR(250) NULL,
  `type` ENUM('PRIMERAS_PLANAS', 'PORTADA_FINANCIERA', 'CARTON', 'COLUMNA_FINANCIERA', 'COLUMNA_POLITICA') NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));



ALTER TABLE `files_pdfs` 
CHANGE COLUMN `type` `type` ENUM('PRIMERAS_PLANAS', 'PORTADA_FINANCIERA', 'CARTON', 'COLUMNA_FINANCIERA', 'COLUMNA_POLITICA') NOT NULL;